#!/bin/bash
# install-cron.sh - wire cleanup-cron.sh into the user's crontab with an env
# wrapper. Writes BATON_* vars to ~/.config/baton/env so cron sees them; creates
# a wrapper that sources them; prints the exact crontab line to paste.
# Idempotent: re-runs preserve an unchanged env file. --dry-run writes nothing.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd -P)"

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then DRY_RUN=1; shift; fi

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
ENV_FILE="$CONFIG_HOME/baton/env"
WRAPPER="$REPO_DIR/tools/cleanup-cron-wrapper.sh"
# Read the knob exactly as the runtime consumers do (cleanup-cron.sh:73,
# session-start.sh:107 both use the bare env form), so the displayed value
# provably matches what the in-session sweep paths actually honor. config.json
# support for this knob is intentionally out of scope here (see decisions.md).
SWEEP_INTERVAL_HOURS="${BATON_SWEEP_INTERVAL_HOURS:-48}"

write_env() {
  local tmp; tmp=$(mktemp "${ENV_FILE}.XXXXXX")
  {
    echo "# Generated by tools/install-cron.sh - sourced by cleanup-cron-wrapper.sh"
    echo "export BATON_PROJECT_DIR=\"${BATON_PROJECT_DIR:-$PWD}\""
    echo "export BATON_ARCHIVE_DIR=\"${BATON_ARCHIVE_DIR:-$HOME/.local/share/baton}\""
    [ -n "${BATON_DIR:-}" ]          && echo "export BATON_DIR=\"$BATON_DIR\""
    [ -n "${BATON_PROGRESS_DIR:-}" ] && echo "export BATON_PROGRESS_DIR=\"$BATON_PROGRESS_DIR\""
  } > "$tmp"

  if [ -f "$ENV_FILE" ] && cmp -s "$tmp" "$ENV_FILE"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
  fi
}

if [ "$DRY_RUN" != "1" ]; then
  mkdir -p "$(dirname "$ENV_FILE")"
  write_env
  cat > "$WRAPPER" <<EOF
#!/bin/bash
# Auto-generated by tools/install-cron.sh - sources env file before running cleanup-cron.
set -u
[ -f "$ENV_FILE" ] && source "$ENV_FILE"
exec "$REPO_DIR/tools/cleanup-cron.sh"
EOF
  chmod +x "$WRAPPER"
fi

echo ""
echo "=== Add this to your crontab (run \`crontab -e\` and paste) ==="
echo "0 0 */2 * * $WRAPPER >> \$HOME/.cache/baton/cron.log 2>&1"
echo "=== End crontab snippet ==="
echo ""
echo "Note: the OS-cron cadence above is FIXED (every 2 days) and is INDEPENDENT of"
echo "BATON_SWEEP_INTERVAL_HOURS. The env knob (currently ${SWEEP_INTERVAL_HOURS}h) governs"
echo "the PRIMARY in-session sweep paths - the SessionStart staleness probe and any"
echo "'cleanup-cron.sh --if-due' run - which self-throttle on that interval."
echo ""
if [ "$DRY_RUN" = "1" ]; then
  echo "(dry-run: no env file or wrapper written, no crontab modification)"
  echo "Would write env file: $ENV_FILE"
  echo "Would write wrapper:  $WRAPPER"
else
  echo "Env file: $ENV_FILE"
  echo "Wrapper:  $WRAPPER"
fi
