#!/bin/bash
# install-cron.sh - wire cleanup-cron.sh into the user's crontab with an env
# wrapper. Writes BATON_* vars to ~/.config/baton/env so cron
# sees them; creates a wrapper that sources them; prints the exact crontab line
# for the user to paste. Idempotent: re-runs preserve existing env file.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd -P)"

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then DRY_RUN=1; shift; fi

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
ENV_FILE="$CONFIG_HOME/baton/env"
WRAPPER="$REPO_DIR/tools/cleanup-cron-wrapper.sh"

mkdir -p "$(dirname "$ENV_FILE")"

write_env() {
  local tmp; tmp=$(mktemp "${ENV_FILE}.XXXXXX")
  {
    echo "# Generated by tools/install-cron.sh - sourced by cleanup-cron-wrapper.sh"
    echo "export BATON_PROJECT_DIR=\"${BATON_PROJECT_DIR:-$PWD}\""
    echo "export BATON_ARCHIVE_DIR=\"${BATON_ARCHIVE_DIR:-$HOME/.local/share/baton}\""
    [ -n "${BATON_DIR:-}" ]          && echo "export BATON_DIR=\"$BATON_DIR\""
    [ -n "${BATON_PROGRESS_DIR:-}" ] && echo "export BATON_PROGRESS_DIR=\"$BATON_PROGRESS_DIR\""
  } > "$tmp"

  if [ -f "$ENV_FILE" ] && cmp -s "$tmp" "$ENV_FILE"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
  fi
}

write_env

cat > "$WRAPPER" <<EOF
#!/bin/bash
# Auto-generated by tools/install-cron.sh - sources env file before running cleanup-cron.
set -u
[ -f "$ENV_FILE" ] && source "$ENV_FILE"
exec "$REPO_DIR/tools/cleanup-cron.sh"
EOF
chmod +x "$WRAPPER"

echo ""
echo "=== Add this to your crontab (run \`crontab -e\` and paste) ==="
echo "0 */48 * * * $WRAPPER >> \$HOME/.cache/baton/cron.log 2>&1"
echo "=== End crontab snippet ==="
echo ""
echo "Env file: $ENV_FILE"
echo "Wrapper:  $WRAPPER"

if [ "$DRY_RUN" = "1" ]; then
  echo "(dry-run: no crontab modification)"
fi
